group 'com.osir.mcp'
version '2.4.0'

subprojects {
    apply plugin: 'java'

    group 'com.osir.mcp'
    version '2.1.0'

    repositories {
        mavenCentral()
        mavenLocal()
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    compileJava {
        options.encoding = 'UTF-8'
        options.compilerArgs << '-parameters'
    }

    compileTestJava {
        options.encoding = 'UTF-8'
    }
}
